### ISSUE TITLE
Several suggested improvements to install.bash

### ISSUE THREAD

**Issue by bwu62** [iquasere/MOSCA#1]
Things I think you should consider changing:

1. Remove Xming install line at beginning of file. This seems to be specifically a Windows program and should not be hard coded into the automated install file.
1. As of writing this, installing conda and then trying to conda install anything runs into SSL errors due to a change in pyOpenSSL. You need to upgrade it to at least 16.2.0 with `python3 -m easy_install --upgrade pyOpenSSL==16.2.0`
1. Conda installs should have an additional -y flag to suppress confirmation
1. Lines 23,31 you shouldn't hard code your own home directory path.
1. Line 25,31 please prepend any comments with a #
1. Line 35 I don't think you need to install aptitude just to install build-essential. Why not add build-essential to line 36 and do both at once?
1. Lines 73,74 are python code and do not belong in a bash file

**Comment by iquasere** [comment]
Greetings

Glad to see some interest in the tool! The install.bash script has not been updated for some time, since I'm working on a docker version of MOSCA. Because of that, the file is now unopperational, but will soon receive several updates and fixes, some of which you referenced here!

**Comment by iquasere** [comment]
The install.bash file was being revamped and should be completely functional and optimized!

**Comment by bwu62** [comment]
Thanks for the revamp. Can you modify the install.bash so that all downloaded software and data files are relative to the current path? Thanks.

**Comment by iquasere** [comment]
Done. Really made no sense to force MOSCA to be installed in home directory, the way it was set it could even create the folders outside of MOSCA's workspace
