### ISSUE TITLE
Mismatch between Wiki and actual config requirements

### ISSUE THREAD

**Issue by ssorgatem** [iquasere/MOSCA#18]
The paranmeter "experiment", according tot he wiki, is "Name of TSV file with information on samples/files/conditions.", but in the code it's just tryong to create a dataframe out of that string, suggesting it ought to be a dict as in the example config.

**Comment by iquasere** [comment]
You are right, I have updated the documentation. The experiments field is set as a dictionary, as per the [file](https://github.com/iquasere/MOSCA/blob/master/config/config.json) available in the repo.

Unfortunately haven't had time to uniformize all informations about MOSCA, as I have to juggle between the wiki, the source code and the [graphical interface](https://iquasere.github.io/MOSGUITO/), if you do find any more errors, please do inform!
