### ISSUE TITLE
Empty Output Directories

### ISSUE THREAD

**Issue by chandnisidhu** [iquasere/MOSCA#2]
Hi, 

I have used my metagenomic data  to check this pipeline. The pipeline worked well but the output directories generated were empty with no information. Please look into the matter. 

nbhb-001-017:MOSCA-master csid$ python main.py --files /Users/csid/Documents/SRP187387_1.fastq /Users/csidhu/Documents/SRP187387_2 -o /Users/csid/Documents/
{   'annotation_database': 'Databases/Annotation/uniprot.dmnd',
    'assembler': 'metaspades',
    'conditions': None,
    'files': [   '/Users/csid/Documents/SRP187387_1.fastq',
                 '/Users/csid/Documents/SRP187387_2'],
    'metaproteomic': False,
    'no_annotation': False,
    'no_assembly': False,
    'no_binning': False,
    'no_preprocessing': False,
    'output': '/Users/csid/Documents',
    'output_level': 'min',
    'type_of_data': 'paired'}

{'files': ['/Users/csid/Documents/SRP187387_1.fastq', '/Users/csid/Documents/SRP187387_2'], 'type_of_data': 'paired', 'assembler': 'metaspades', 'annotation_database': 'Databases/Annotation/uniprot.dmnd', 'output': '/Users/csidhu/Documents', 'no_preprocessing': False, 'no_assembly': False, 'no_annotation': False, 'no_binning': False, 'output_level': 'min', 'metaproteomic': False, 'conditions': None}
Files
Experiment1
MG files: /Users/csid/Documents/SRP187387_1.fastq
Experiment2
MG files: /Users/csid/Documents/SRP187387_2
Type of data: paired
Assembler: metaspades
Annotation database: Databases/Annotation/uniprot.dmnd
Output: /Users/csid/Documents
No preprocessing: False
No assembly: False
No annotation: False
No binning: False
Output level: min
Metaproteomic: False
Conditions: None
Creating directories at /Users/csid/Documents
Created /Users/csid/Documents/Preprocess/FastQC
Created /Users/csid/Documents/Preprocess/Trimmomatic
Created /Users/csid/Documents/Preprocess/SortMeRNA
Created /Users/csid/Documents/Assembly
Created /Users/csid/Documents/Annotation
Created /Users/csid/Documents/Metatranscriptomics_analysis
Splitting reads in /Users/csid/Documents/SRP187387_1.fastq to /Users/csid/Documents/Preprocess/SRP187387_1_R1.fastq and /Users/csid/Documents/Preprocess/SRP187387_1_R2.fastq.
Handling SRP187387_1
Preprocessing of metagenomic reads has begun
Assembly has begun
Annotation has begun
Binning has begun
Splitting reads in /Users/csid/Documents/SRP187387_2 to /Users/csid/Documents/Preprocess/SRP187387_2_R1.fastq and /Users/csid/Documents/Preprocess/SRP187387_2_R2.fastq.
Handling SRP187387_2
Preprocessing of metagenomic reads has begun
Assembly has begun
Annotation has begun
Binning has begun
nbhb-001-017:MOSCA-master csid$

**Comment by iquasere** [comment]
MOSCA will soon be updated (probably in 2-3 days) and that problem should be solved. I do however advise that you define another folder as output, since that parameter is the name of the MOSCA project, and all files will be outputed to it. MOSCA automatically creates a the new folder if it doesn't exist.

**Comment by chandnisidhu** [comment]
Hi,

I created new folder as output directory. The pipeline executes but did not give any output. All directories were empty as before. When will it be updated?

**Comment by iquasere** [comment]
MOSCA has finally been updated! I would advise cloning the repository again and rerunning the install.bash file again. This new version still lacks some testing, and only in a couple of days will I be sure it is stable to run. The dockerization is also not complete, but will be in a couple of days!

**Comment by chandnisidhu** [comment]
Hi,
Thanx for the updated version.  I have tried it but after cloning and installing dependencies, I didn't find any main.py and it is not working. Please help.

**Comment by iquasere** [comment]
The main script is now mosca.py, so the command has changed to python mosca.py if on the MOSCA directory. The README file will be updated on April, after all these changes are sufficiently curated and tested!

**Comment by iquasere** [comment]
README.md has been updated and everything should be functional now, as stated in the instructions!

**Comment by chandnisidhu** [comment]
Hi,

Thank you for the information. Job is already running :)

**Comment by iquasere** [comment]
Would really like to know how it ended. Yours is the first project that I know of outside of our lab to use MOSCA!

**Comment by iquasere** [comment]
I'll assume that after all the debugging that has happened, MOSCA now fills its directories. If the problem persist, please don't hesitate in reopening the issue!
