### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by Rodrigo-Ribeiro26** [iquasere/MOSCA#20]
I tried to install MOSCA through conda biotools and I get the following error: 
![ACNY2zPB](https://github.com/iquasere/MOSCA/assets/97360283/ec3314db-2391-4923-b310-4deb758769c6)

**Comment by iquasere** [comment]
`conda install -c conda-forge -c bioconda mosca`, as explained in the [wiki](https://github.com/iquasere/MOSCA/wiki/Install-MOSCA-%F0%9F%93%A6).

If installation doesn't work with conda, try with mamba:
```
conda install -c conda-forge mamba
mamba install -c conda-forge -c bioconda mosca
```
