### ISSUE TITLE
Issue with metaquast after assembly

### ISSUE THREAD

**Issue by ImadhAzeez** [iquasere/MOSCA#21]
Hi, 

I've been having issues running MOSCA for RNAseq sequences, specifically after assembly, where I keep getting an issue with Metaquast, in the error, it seems like there is no contig.fasta or scaffold.fasta file. The assembly seems to result in a transcripts.fasta file, which I assume to be the output file expected for rnaSPADES?

Here is the outcome.

![Screen Shot 2023-08-25 at 4 34 37 pm](https://github.com/iquasere/MOSCA/assets/125558976/ef53c781-b174-402c-9f3e-46ba70160030)

Hopefully you will be able to help?

Kind regards,
Imadh

**Comment by iquasere** [comment]
Sorry for the late response, and thank you for reporting on this bug!

I'll be looking at this problem the following days. Also, are you using the latest version of MOSCA - `2.1.0`?

**Comment by iquasere** [comment]
With MOSCA `2.2` launched, and this bug not showing up, I'm closing the issue. If it persists, please don't hesitate reopening it.
